### ISSUE TITLE
Using Sinatra Templates

### ISSUE THREAD

**Issue by joshturge** [cherryramatisdev/api-with-dry-ruby#1]
Hi,

I came across this project and really like the structure. I'm attempting to integrate Sinatra's templating functionality with this project structure and can't seem to figure out how to do so.

Specifically I want to use Sinatra's erb method in the controllers like so:

```ruby
module Controllers
  class User
    def initialize
      @service = Application['services.user']
    end

    def index
      users = @service.list_all
      erb :user_list
    end
  end
end
```

Would you be able to point me in the right direction?

Thanks

**Comment by cherryramatisdev** [comment]
Hey @joshturge! Glad that you liked the project, I manage to include some example of templating on this particular commit: https://github.com/cherryramatisdev/api-with-dry-ruby/commit/af5589e0233615e7404ff80af689ef8a6b8bf626

It's surely not perfect, I would improve the helper for erb to use the one from sinatra but I didn't spent a lot of time on this

If you want to continue discussing further this questions, i'm glad to help with anything 🩷 Hope this give you insight to figure out the missing parts

**Comment by joshturge** [comment]
Thanks

**Comment by cherryramatisdev** [comment]
always a pleasure to help
